version: 2

iac:
  ignored-policies:
    - 'GG_IAC_0047'
sca:
  ignored-paths:
    - 'terraform/dir/'
  ignored-vulnerabilities:
    - identifier: 'CVE-2024-1300'
      path: 'pom.xml'
      comment: 'my-comment'
