default_stages: [push]
repos:
  - repo: local
    hooks:
      - id: ggshield-local
        name: GitGuardian Shield
        entry: /home/jonathangriffe/.local/share/virtualenvs/ggshield-tYsDJ0Pv/bin/ggshield iac scan pre-push
        language: system
        stages: [push]
        pass_filenames: false
