name: Scan Secrets GitGuardian

on:
  pull_request:
    branches: 
      - develop
      - main
      - master
      - release/**/*

permissions:
  # required for all workflows
  security-events: write

  # only required for workflows in private repositories
  actions: read
  contents: read

jobs:
  scan-secrets-gitguardian:
    name: Scan Secrets GitGuardian

    strategy:
      fail-fast: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Gitguardian scan actions
        uses: GitGuardian/ggshield-action@master
        with:
          args: -v --json -o actions-gitguardian-result.json --log-file actions-gitguardian-result.log --with-incident-details --exit-zero
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.base }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}
      - name: Archive  results
        uses: actions/upload-artifact@v4
        with:
          name: ggshield-report
          path: actions-gitguardian-result.json
